config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root "pins#index"

  get "/feedback" => "comments#new"
  post "/feedback" => "comments#create"
  
  get "/users" => "users#index"
  get "/users/:id" => "users#show"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user

  def username
    User.find(self.user_id).name
  end
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { medium: "300x300>", :thumb => "100x100>"}
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

validates :image, presence: true
validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :pins
   has_many :comments

   validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_filter :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comments = Comment.all
    @comment = Comment.new
    render 'pages/feedback', layout: 'application'
  end

  def create
    @comment = Comment.new(comment_params)
      @comment.user_id = current_user.id
      if @comment.save
        respond_to do |format|
          format.html {redirect_to feedback_path}
          format.json {render json: @comment}
        end
      else
        render plain: 'There was an error submitting feedback. Please try again'
      end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]


  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @pins}
    end
  end


  def show
    @pin = Pin.find(params[:id])
      respond_to do |format|
        format.html {render :show}
        format.json {render json: @pin}
      end
  end


  def new
    @pin = current_user.pins.build
  end

 
  def edit
  end

 
  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.' 
    else
      render action: 'new' 
    end
  end

 
  def update
    if @pin.update(pin_params)
       redirect_to @pin, notice: 'Pin was successfully updated.' 
    else
       render :edit 
    end
  end

  def destroy
    @pin.destroy
    respond_to do |format|
      format.json { render status: 200 }
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
    end
    
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  #    respond_to do |f|
   #     f.html {render :index}
    #    f.json {render json: @users}
    #  end
  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pinterest", root_path, class: "navbar-brand" %>
    </div><!-- /.container -->


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Feedback", feedback_path %></li>
        <li>
          <%= link_to new_pin_path do %>
            <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
        </li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterest</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
  	
  	<%= render 'layouts/header' %>

  	<div class="container">
  		<% flash.each do |name, msg| %>
  		<%= content_tag(:div, msg, class: "alert alert-info") %>
  		<% end %>

  <%= yield %>

  	</div>
    
  </body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my app!</h1>
	<p>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>

	</p>
</div>

app/views/pages/about.html.erb
<div class="panel panel-default">
  <h1>About</h1>
    <p> Hey! My name is James Novak and I am a full stack web developer. Feel free to sign up and create some pins! If you're interested checkout the github repo <%= link_to 'here', "https://github.com/jamesnvk/pinterest", target: "_blank" %>.</p>
</div>

app/views/pages/feedback.html.erb
  <table class="table table-striped">
    <thead>
      <tr> 
        <th>#</th> <th>Username</th> <th>Comment</th>
      </tr> 
    </thead> 
    <tbody id="feedbackResults">
      <% @comments.each do |comment| %>
       <tr> 
          <th scope="row"><%= comment.id %></th> 
          <td><%= comment.username %></td> <td><%= comment.content %></td> 
      </tr>
      <% end %>
    </div>
     </tbody>
  </table>



<% if user_signed_in? %>
  <%= form_for @comment, url: '/feedback' do |f| %>
    <%= f.text_area :content %><br></br>
    <%= f.submit %>
    <% end %>
<% else %>
  <h4> Please <%= link_to "Login", new_user_session_path %> to submit feedback. Thank you! </h4>
<% end %>

<script id="comment-template" type="text/x-handlebars-template">
   <tr> 
      <th scope="row">{{id}}</th> 
      <td><%= current_user.name %></td> <td>{{content}}</td> 
  </tr>
</script>

<script id="pin-template" type="text/x-handlebars-template">
   <div id="pinResults">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
          <div class="panel-heading center">
          </div>
          <div class="panel-body">
            <p>{{description}}</p>
            <p><strong>{{username}}</strong></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</script>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to my app!</h1>
	<% if user_signed_in? %>
		
	<% else %>
	<p>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>

	</p>

	<% end %>

</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: {multipart: true} do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group" >
    <%= f.submit class: "btn btn-primary btn-lg"%>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div class="container" id="pins">
    <% @pins.each do |pin| %>
    <div class="row">
          <div class="col-md-3" id="pin" data-id="<%=pin.id%>">
            <div class="box panel panel-default">
            <%= link_to image_tag(pin.image.url(:medium)), pin %>
              <%= pin.description %><br/>
              <strong><%= pin.user.name if pin.user %></strong>
              <% if pin.user == current_user %>
                <div class="actions">
                  <%= link_to edit_pin_path(pin) do %>
                  <span class="glyphicon glyphicon-edit"></span> 
                  Edit
                  <% end %>
                  <%= link_to pin, method: :delete, class: 'deletePin', data: { confirm: 'Are you sure?' } do %>
                    <span class="glyphicon glyphicon-trash"></span> Delete
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
  </div>



<div class="center">
  <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

<script id="pin-template" type="text/x-handlebars-template">
  <div class="box panel panel-default" id="pin" data-id="{{id}}">
    <div class="panel-body">
      {{description}}<br/>
      <strong>{{username}}</strong>
      </div>
    </div>
</script>

<script id="comment-template" type="text/x-handlebars-template">
    <tr>
      <h1>{{title}}</h1>
      <div class="body">
        {{body}}
      </div>
    </div>
</script>

app/views/pins/new.html.erb
<h1>New Pin</h1>

  <%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %><br>
<%= link_to 'Next Pin', '#', class: "js-next", data: {id: @pin.id} %>

<div id="pinResults">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="panel panel-default">
        <div class="panel-heading center">
          <%= image_tag @pin.image.url(:medium) %>
        </div>
        <div class="panel-body">
          <p><%= @pin.description %></p>
          <p><strong><%= @pin.user.name if @pin.user %></strong></p>

          <% if @pin.user == current_user %>
           <%= link_to edit_pin_path(@pin) do %>
          	<span class="glyphicon glyphicon-edit"></span>
          	Edit
        <% end %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

<script id="pin-template" type="text/x-handlebars-template">
   <div id="pinResults">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <div class="panel panel-default">
          <div class="panel-heading center">
          </div>
          <div class="panel-body">
            <p>{{description}}</p>
            <p><strong>{{username}}</strong></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</script>


<script id="comment-template" type="text/x-handlebars-template">
   <tr> 
      <th scope="row">{{id}}</th> 
      <td><%= current_user.name %></td> <td>{{content}}</td> 
  </tr>
</script>

app/views/users/index.html.erb
<% @users.all.each do |u| %>
    <div id="data-<%=u.id%>">
    <li><%= u.name %></li>
    </div>
    <button class="load-more" data-id="<%=u.id%>">Load comments</button>
<% end %>

<script id="pin-template" type="text/x-handlebars-template">
  <div class="box panel panel-default" id="pin" data-id="{{id}}">
    <div class="panel-body">
      {{description}}<br/>
      <strong>{{username}}</strong>
      </div>
    </div>
</script>

<script id="comment-template" type="text/x-handlebars-template">
    <tr>
      <h1>{{title}}</h1>
      <div class="body">
        {{body}}
      </div>
    </div>
</script>

app/views/users/show.html.erb
<%= @user.name %>